platform: "nitro"
nonclave:
  route: "app/v1"
  measurement: |
    {
      "pcrs": {
        "0": "pKxHS+cImWgkF+3+jRR0EJhLuzvixg0gVOsR7gv/9MLUwrWZFhWoFuDc8sSUzFTn",
        "1": "S01bNmGz78EpIJAMgOEm5M54PFIt5sAqKlv3rzorkye4Z3bxiOS+HBxAShKdvaST",
        "2": "23GycBcuSEjKkVrM3MVsryXA3oRbi9rhttPDERBMghTROuT15gKD+Og5mapg4Mre",
        "3": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "4": "qCPabIHXU+nhGcZdNOlh6t6ts85vPpXbEhRxY1f+azLcAvahbgsBN+sKbCfnE+yq",
        "8": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
      },
      "module_id": ""
    }
