platform: "tdx"
nonclave:
  args:
    domain: "bearclave.tee"
  measurement: |
    {
      "tee_tcb_svn": "DQEIAAAAAAAAAAAAAAAAAA==",
      "mr_seam": "SJ5YXxxUvFoCBmyMbsIWGf8DNOxvIeB+KjUgLFkYN4nIBX59l91ZG7CDFLGFgZ5y",
      "mr_signer_seam": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "seam_attributes": "AAAAAAAAAAA=",
      "td_attributes": "AAAAEAAAAAA=",
      "xfam": "5wAGAAAAAAA=",
      "mr_td": "pYROiIl7cMMYvvkp7039bHMExSxLycPzkTLw/czs8+tbq3ARDuQqElCaMcA3KIaU",
      "mr_config_id": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "mr_owner": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "mr_owner_config": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "rtmrs": [
        "",
        "541YF6n1DTDLxiDYwkfmmWOptN82LDCu/6SnPGQ+c1dPtqSGHWuDqNwJWzkvN+Ae",
        "lfXvmOAaKoL3eRi2SxkYsp2ypIr4ng9XdCBy+HxNklgRzNdMwFQNavJaVnHC3/Nl",
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
      ]
    }
