platform: "tdx"
nonclave:
  measurement: |
    {
      "tee_tcb_svn": "CAEIAAAAAAAAAAAAAAAAAA==",
      "mr_seam": "v7NgrI5iM6G8oUM8r3OC2VwWW0p3+wC/FDXloI8wDN/q1e5oRhr9m2xyjc51NGAt",
      "mr_signer_seam": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "seam_attributes": "AAAAAAAAAAA=",
      "td_attributes": "AAAAEAAAAAA=",
      "xfam": "5wAGAAAAAAA=",
      "mr_td": "QJwM0+Y9nqVNgXz4UZg6IgExJiZkrIzQLMai4Z/SkdL90MwDXXeJuYKkOpKkQkyZ",
      "mr_config_id": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "mr_owner": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "mr_owner_config": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "rtmrs": [
        "JWT8YbpCfP1zdu3YK80eZRN6sIq3Y5Fn7/T7gNH4ULSXwP3x86OUPSMRpppE203N",
        "541YF6n1DTDLxiDYwkfmmWOptN82LDCu/6SnPGQ+c1dPtqSGHWuDqNwJWzkvN+Ae",
        "lfXvmOAaKoL3eRi2SxkYsp2ypIr4ng9XdCBy+HxNklgRzNdMwFQNavJaVnHC3/Nl",
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
      ]
    }
